### ISSUE TITLE
taskCacheDetailedDiagnosticsInit.gradle missing

### ISSUE THREAD

**Issue by sayniv** [gradle/task-output-cache-demos#7]
The section on "Diagnosing the task cache" (https://github.com/gradle/task-output-cache-demos/blob/master/docs/diagnosing-task-cache.md) refers to a file named taskCacheDetailedDiagnosticsInit.gradle at the location https://raw.githubusercontent.com/gradle/gradle/master/gradle/taskCacheDetailedDiagnosticsInit.gradle

However, trying to access this file returns a 404.

**Comment by big-guy** [comment]
@sayniv I lot of the documentation here has been moved to https://guides.gradle.org/using-build-cache/#debugging_and_diagnosing_cache_misses
